name = "gfx_sandbox"
description = "GFX Sandbox"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["gnat/gfx_sandbox.gpr"]

[configuration]
generate_c = false
generate_ada = false

[[depends-on]]
a0b_base = "*"
gfx_drawing = "~0.1.0-dev"

[[pins]]
gfx_core = { path='subprojects/gfx-core' }
gfx_drawing = { path='subprojects/gfx-drawing' }
